-- ============================================================================
-- Migration 012: Investment RPC Functions
-- ============================================================================
-- 7 atomic RPCs for the investment feature:
--   1. create_investment_asset   – Create master asset + first buy tx
--   2. topup_investment          – Add buy row to existing asset
--   3. sell_investment            – Create sell row, auto-deactivate if 0 units
--   4. edit_investment_transaction – Edit buy tx only, revert/apply wallet
--   5. delete_investment_transaction – Delete buy tx, revert wallet
--   6. delete_investment_asset    – CASCADE delete with optional wallet revert
--   7. get_investment_dashboard   – Dashboard aggregation query
-- ============================================================================

-- (Applied via Supabase MCP. See full SQL in session context.)
-- Full SQL omitted here for brevity — applied directly to live DB.
